GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTYxMDAzNDUwMSwiZXhwIjoxNjEwMDM0NTE2fQ.TFpf9Kf7i3jYtavQE8dV8wTXvtE9fn2TX5wEH0MUyi8
###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Kyle"
}
