GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTYxMDAzMjY4Nn0.0_GO6SHEDnucxgtclPwrPHSgEfcl7J0Fh9tk5tvn7y8
###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Kyle"
}
