GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTYxMDAzODMyNywiZXhwIjoxNjEwMDM4MzU3fQ.Giijq6pi3d6vY_238rlFTztV4_atxDprckXa3Gzvj50
###
POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTYxMDAzNzc4OH0.ehV9tj1QaO_GU1BT8ae1_a_Rq5Y1ezFcvhR70fBG4zU"
}
###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Kyle"
}
